export const INSTANT_SEND = 'INSTANT';
export const SUBTRACT_NOW = 'SUBTRACT_NOW';
export const FUTURE = 'FUTURE';
export const FUTURE_CREDIT_RECIPIENT_COMPLETE =
	'FUTURE_CREDIT_RECIPIENT_COMPLETE';
